export type Feature = {
  id: number;
  kind: string;
  x: number;
  y: number;
  y2?: number;
  sag?: number;
  width: number;
  active: boolean;
  variant?: number;
  appearance?: { biome: number; roof_pitch: number; facade_height: number; door_offset: number; window_spacing: number; post_offsets: [number,number]; palette: number; motion_amplitude: number; motion_frequency: number; motion_phase: number; attachments?: [number,number] | null };
};
export type Goal = {
  label: string;
  value: number;
  target: number;
  complete: boolean;
  id?: string;
  scope?: "run" | "total" | "combo";
  metric?: string;
};
export type Challenges = { level: number; total: number; complete: boolean; current_goals: Goal[]; levels: { level: number; goals: Goal[]; complete: boolean; unlocks: number | null }[]; history: number[]; migrated: boolean };
export type Rider = {
  name: string;
  ability: string;
  description: string;
  level: number;
  color: string;
};
export type State = {
  x: number;
  y: number;
  angle: number;
  grounded: boolean;
  speed: number;
  vx?: number;
  vy?: number;
  alive: boolean;
  zen: boolean;
  score: number;
  coins: number;
  distance: number;
  combo: number;
  combo_points: number;
  tricks?: { name: string; count: number; points: number }[];
  banked_tricks?: { name: string; count: number; points: number }[];
  banked_score?: number;
  bank_time?: number;
  cooldown: number;
  power: number;
  immune: number;
  wing: number;
  scarf_length?: number;
  wing_on: boolean;
  wing_ready?: boolean;
  proximity?: boolean;
  magnet?: number;
  feather?: number;
  hover?: number;
  shield?: boolean;
  boost?: number;
  boost_max?: number;
  gaps?: [number, number][];
  chase?: { x: number; y: number; previous_x: number; previous_y: number; speed: number } | null;
  camp?: { x: number; y: number };
  rider: number;
  riders: Rider[];
  features: Feature[];
  rock_outline?: [number, number][];
  terrain: {
    x: number;
    y: number;
    gap: boolean;
    slope?: number;
    vy?: number;
  }[];
  terrain_segments?: { x0: number; x1: number; y0: number; y1: number; m0: number; m1: number }[];
  level: number;
  goals: Goal[];
  progress: { best: number; coins: number; wallet: number; runs: number; helmets: number; rescue_picks: number; upgrades: { magnet: number; feather: number; wingsuit: number; scarf: number } };
  notice: string;
  time: number;
  terrain_time?: number;
  horde_phase?: number;
  horde_flow?: number;
  previous?: {
    x: number;
    y: number;
    angle: number;
    time: number;
    terrain_time: number;
  };
  seed?: number;
  ruleset?: number;
  rope_states?: Record<string, { load: number; broken_at: number | null; ridden_to: number }>;
  grind_distance_m?: number;
  biome?: number;
  slow?: boolean;
  poison?: number;
  exposure?: number;
  rail?: number | null;
  wall?: number | null;
  effects?: { id: number; phase: number; danger: boolean }[];
};
export type Mode = "menu" | "play" | "crash" | "pause" | "result";
export type ShopItem = { id: string; name: string; group: string; level: number; max: number; price: number | null; effect: string; affordable: boolean; locked?: boolean; requirement?: string | null };
